### ISSUE TITLE
Add more common commands to Containerfile

### ISSUE THREAD

**Issue by thomagos** [IBM/csm-dach-cloud-native-labs#10]
As a new developer, 
I want to learn the most common Containerfile commands during the workshop, 
so I can start right away with 95% of the requests I'm given to.

### Acceptance criteria

- [x] Add `ENV` and `ARG` to Containerfile and explain
- [x] Add `ADD` and `COPY` to Containerfile and explain the difference
- [x] Set `WORKDIR`

**Comment by RapTho** [comment]
@tschwaerzl I love your user story! I am confident we now manage to pass the acceptance criteria. If so, may I ask you to close this issue? Thanks for your useful input!
